### ISSUE TITLE
Model used to generate category_embeddings.npy

### ISSUE THREAD

**Issue by Issac-Westcott** [Sonettoo/AeroGen#3]
Hi,

Thank you for providing the category_embeddings.npy. I’d like to ask for clarification on the specific CLIP model used to generate these embeddings. Was it a vanilla model (e.g., openai/clip-vit-base-patch32) or a fine-tuned version?

Thanks!

**Comment by Sonettoo** [comment]
hi,we use the vanilla model openai/clip-vit-large-patch14

**Comment by Issac-Westcott** [comment]
> hi,we use the vanilla model openai/clip-vit-large-patch14

Got it, thanks!
