### ISSUE TITLE
Model Loading Error

### ISSUE THREAD

**Issue by gy65896** [Sonettoo/AeroGen#4]
Thank you for your excellent work. I found that `cond_stage_model.transformer.text_model.embeddings.position_ids` is missing when loading `./ckpt/aerogen_diorr_last.ckpt`. What is the reason?

**Comment by gy65896** [comment]
And, I would like to know when the training code will be made public.

**Comment by Sonettoo** [comment]
Hi, first you need to download the pre-trained model, in addition the training has been published

**Comment by Sirius-Li** [comment]
do you solve the problem?

**Comment by gy65896** [comment]
I find the reason. Due to the different `transformers' package being installed, this wrong will occur. You can use this command to solve it `pip install transformers==4.24.0'.

**Comment by Sirius-Li** [comment]
Thanks a lot for help，I also find that is caused by transformer version, change model.load_state_dict(load_state_dict(ckpt_file_path, location='cpu')) to model.load_state_dict(load_state_dict(ckpt_file_path, location='cpu'),strict=False) can also solve the problem(in inference.inference.py line 54)

**Comment by gy65896** [comment]
I find the reason. Due to the different `transformers` package being installed, this wrong will occur. You can use this command to solve it `pip install transformers==4.46.3`.
