### ISSUE TITLE
The pretrained YOLO weights for calculating the YOLO score.

### ISSUE THREAD

**Issue by fayewong666999** [Sonettoo/AeroGen#5]
This is a very good work for the remote sensing data generation. To follow up on your work, I would like to obtain the pre-trained YOLO weights required for calculating the YOLO score, so that I can align with the results in your paper. Is that possible? Thank you!

**Comment by Sonettoo** [comment]
Hi, sorry for the late reply, you can provide your email if required. To facilitate sending the file, the code here is not organised, we refer to the following code to implement the metrics calculation [YoLo v8](https://github.com/JohnPPinto/Object_Detection_Satellite_Imagery_Yolov8_DIOR/) and [YoLo v9-obb](https://github.com/YellowTigerr/RSO-YOLO)

**Comment by fayewong666999** [comment]
My private email is 1179828304@qq.com, thank you~

**Comment by fayewong666999** [comment]
My private email is wenzwong202@gmail.com, thank you!
